language: rust
sudo: false
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
       - FEATURES='all'
       - BENCH=1
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES") &&
      cargo doc --verbose --features "$FEATURES"
