language: rust
sudo: false
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env:
       - FEATURES='all'
       - BENCH=1
    - rust: nightly
      env:
       - FEATURES='pattern'
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --lib &&
      ([ -z "$FEATURES" ] || cargo test --verbose --features "$FEATURES" ) &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES") &&
      cargo doc --verbose --features "$FEATURES"
